import { NextResponse } from "next/server";
import { runAIReview } from "@/lib/ai-review";

export async function POST(req: Request) {
    try {
        const event = req.headers.get("x-github-event");

        // We only care about PR events
        if (event !== "pull_request") {
            return NextResponse.json({ message: `Ignored event type: ${event}` });
        }

        const payload = await req.json();
        const action = payload.action;

        // When a PR is opened, or code is pushed (synchronized)
        if (action === "opened" || action === "synchronize") {
            const owner = payload.repository.owner.login;
            const repo = payload.repository.name;
            const pullNumber = payload.pull_request.number.toString();

            console.log(`[Webhook] Triggering AI Review for ${owner}/${repo} PR #${pullNumber}`);

            // Run the review synchronously (forces re-run on fresh commit)
            const aiData = await runAIReview(owner, repo, pullNumber, true);

            // Post back to GitHub if PAT is available
            const pat = process.env.GITHUB_PAT;
            if (pat) {
                console.log(`[Webhook] Publishing AI findings back to GitHub PR...`);

                const findings = Array.isArray(aiData.feedback) && aiData.feedback.length > 0
                    ? aiData.feedback.map((f: any) => `- **[${f.severity || "Finding"}]** \`${f.file}\`: ${f.comment}`).join("\n")
                    : "- No critical code findings detected.";

                const commentBody = [
                    `## 🧠 Assess.ai Executive Summary`,
                    aiData.summary || "Review completed.",
                    `\n### 🔍 Actionable Findings:`,
                    findings,
                    `\n---\n*Automated review generated by [Assess.ai](http://localhost:3000)*`
                ].join("\n\n");

                const ghRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues/${pullNumber}/comments`, {
                    method: 'POST',
                    headers: {
                        'Authorization': `token ${pat}`,
                        'Accept': 'application/vnd.github.v3+json',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ body: commentBody })
                });

                if (!ghRes.ok) {
                    console.error("[Webhook] Failed to post comment to GitHub", await ghRes.text());
                } else {
                    console.log(`[Webhook] Successfully published to GitHub!`);
                }
            } else {
                console.warn("[Webhook] GITHUB_PAT not set in environment variables. Assessment cached locally but not published to GitHub repository timeline.");
            }

            return NextResponse.json({ success: true, message: `Review generated and processed for PR #${pullNumber}.` });
        }

        return NextResponse.json({ message: `Action '${action}' not tracked.` });
    } catch (err: any) {
        console.error("Webhook Error:", err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
